# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


target 'TempoExample' do
    #use_frameworks!
	pod 'Tempo_ios_sdk', :path => '..'
    pod 'SideMenu'
end
