site_name: Tempo iOS SDK
pages:
  - Home: index.md
  - API Reference:
    - Installation: reference/init.md
    - Services: reference/services.md
    - Examples: reference/mbtiles.md
theme: readthedocs
use_directory_urls: false
plugins:
  - search
